version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/doc-pusher
    environment:
      - PATH: /root/node/bin:/root/yarn/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
    steps:
      - checkout
      - restore_cache:
          keys:
            - doc-pusher-{{ .Branch }}-{{ checksum "/root/frontends/new_horizon/yarn.lock" }}-{{checksum "/root/frontends/new_horizon/support/storybook/yarn.lock"}}
            - doc-pusher-{{ .Branch }}
      - run: yarn
      - save_cache:
          paths:
            - /root/.cache/yarn
          key: doc-pusher-{{ .Branch }}-{{ checksum "/root/frontends/new_horizon/yarn.lock" }}-{{checksum "/root/frontends/new_horizon/support/storybook/yarn.lock"}}
  deploy-master:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/doc-pusher/frontends/new_horizon/support/storybook
    environment:
      - PATH: /root/node/bin:/root/yarn/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
    steps:
      - checkout:
          path: ~/doc-pusher
      - restore_cache:
          keys:
            - doc-pusher-{{ .Branch }}-{{ checksum "/root/frontends/new_horizon/yarn.lock" }}-{{checksum "/root/frontends/new_horizon/support/storybook/yarn.lock"}}
            - doc-pusher-{{ .Branch }}
      - run: yarn
      - run: cd /root/doc-pusher/frontends/new_horizon && yarn
      - save_cache:
          paths:
            - /root/.cache/yarn
          key: doc-pusher-{{ .Branch }}-{{ checksum "/root/frontends/new_horizon/yarn.lock" }}-{{checksum "/root/frontends/new_horizon/support/storybook/yarn.lock"}}
      - run: npm run ci_release
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-job:
          filters:
            tags:
              only: /.*/ # run build job for all branches and all tags push
      - deploy-master:
          requires:
            - build-job
          filters:
            branches:
              only: main
