version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/doc-pusher
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-proj-dep-{{ checksum "package.json" }}
            - node-proj-dep-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-proj-dep-{{ checksum "package.json" }}
  deploy-master:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/doc-pusher/ui/support
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-proj-dep-{{ checksum "package.json" }}
            - node-proj-dep-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-proj-dep-{{ checksum "package.json" }}
      - run: node release.js
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-job:
          filters:
            tags:
              only: /.*/ # run build job for all branches and all tags push
      - deploy-master:
          requires:
            - build-job
          filters:
            branches:
              only: master
