version: 2
jobs:
  deploy-master:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/doc-pusher/frontends/new_horizon
    environment:
      - PATH: /root/node/bin:/root/yarn/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
    steps:
      - checkout:
          path: ~/doc-pusher
      - restore_cache:
          keys:
            - doc-pusher-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{checksum "support/storybook/yarn.lock"}}
            - doc-pusher-{{ .Branch }}
      - run: yarn
      - run: cd support/storybook && yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: doc-pusher-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{checksum "support/storybook/yarn.lock"}}
      - run: cd support/storybook && npm run ci_release
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-master:
          filters:
            branches:
              only: main
